Nvt 398 exercicio1 frontend
EricaLima570/php pull request #1
Opened 2023-04-06 02:32 UTC by EricaLima570

2023-04-22 13:35 UTC, edmargomes requested changes

2023-04-22 13:35 UTC, edmargomes commented on readme.md
> +P.S: Certifique-se de estar usando a identação certa nesse comando.
Pode remover essa explicação pois você ja criou o arquivo docker-compose e versionou

2023-04-23 12:36 UTC, FranciscoWallison approved these changes
Como recomendado na revisão, os comentários foram removidos e um novo texto foi adicionado.

2023-04-23 13:01 UTC, FranciscoWallison commented on readme.md
> +P.S: Certifique-se de estar usando a identação certa nesse comando.
Como recomendado na revisão, os comentários foram removidos e um novo texto foi adicionado.

2023-04-23 13:04 UTC, merged